---
version: "3"
services:
  python:
    build: .
    tty: true
    container_name: qr-coder
    environment:
      - DEBUG=True
    volumes:
      - .:/var/task/qr-coder:delegated
    ports:
      - "8000:8000"
