name: Deploy main branch
on: push
#on:
#  push:
#    branches:
#      - main
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        python-version: [ "3.9" ]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: |
        python -c "import sys; print(sys.version)"
        npm --version
        npm install -g serverless@3.x
        npm install -g --save-dev serverless-prune-plugin
        npm install -g --save-dev serverless-wsgi
        npm install -g --save-dev serverless-python-requirements

        cd ${{ github.workspace }}
        serverless deploy --verbose
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         SERVERLESS_ACCESS_KEY: ${{ secrets.SLS_ACCESS_KEY }}
