name: Run Tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Run tests
        run: poetry run pytest
